version: "3"

services:
    database:
        image: mysql:latest
        container_name: demo_db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo_db
        ports:
            - 3306:3306
        volumes:
            - demo_data:/var/lib/mysql
    api:
        image: backend/demo
        container_name: demo_api
        build: backend/demo
        environment:
            MYSQL_HOST: database
        depends_on:
            - database
        ports:
            - 8080:8080
        restart: always
    web:
        image: frontend/demo
        container_name: demo_web
        build: frontend/demo
        ports:
            - 5000:5000

volumes:
    demo_data:
